# Backpropogation

`Backpropogation` is the algorithm used in NNs to update the **weights** and **biases**.

In other words, it is the algorithm that operates over our functions in the NN (**loss**, **activations**, etc...) and determines the affect that each input has on these functions.

`Backpropogation` uses **derivatives** and **partial** derivatives to achieve this

---------------

Before implementing `backpropogation` for a full NN, lets practice with the algorithm first by applying it to ReLU first.

In [1]:

print("Full forwards pass through a single neuron and ReLU\n")

# forward pass 
x = [1.0, -2.0, 3.0] # inputs
w = [-3.0, -1.0, 2.0] # weights
b = 1.0 # bias

# multiplying inputs by weights 
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
print(f"{xw0 = }\n{xw1 = }\n{xw2 = }")

# weighted sum (received by the first hidden layer)
z = xw0 + xw1 + xw2 + b
print(f"\n{z = } (weighted sum)")

# ReLU
ReLU = max(z,0)
print(f"{ReLU = }")

Full forwards pass through a single neuron and ReLU

xw0 = -3.0
xw1 = 2.0
xw2 = 6.0

z = 6.0 (weighted sum)
ReLU = 6.0


Recall that the `derivative` of $ReLU()$ with respect to its input is $1$ **if the input is greater than 0** and $0$ otherwise:

<font size="5"> $f(x) = max(x,0) ⟶ \frac{d}{dx}f(x) = 1 (x\gt 0)$ </font>

Now that we've taken the **weighted sum** (`z`) and passed it through `ReLU`, we hae completed a full **`forward pass`**. 

Now, we can start backpropogating. 

First, we take the **derivative** of `ReLU`

In [3]:

#? FORWARD PASS

x = [1.0, -2.0, 3.0] 
w = [-3.0, -1.0, 2.0] 
b = 1.0 
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
z = xw0 + xw1 + xw2 + b
ReLU = max(z,0)
           
           
#! BACKWARD PASS            

# derivative from the next layer (randomly chosen just for this example)         
dvalue = 1.0           

# derivative of ReLU with respect to z and the chain rule: dvalue is the derivative from the next layer
# 1 if input (z) is greater than 0 else 0
drelu_dz = dvalue * (1. if z > 0 else 0.)
print(drelu_dz)

1.0


Moving backward, the next function that comes immediately before the activation is the **weighted sum** (the sum of the multiplied $xw$ pairs).

This means that we want to calculate the **partial derivative** of the sum function and `using the chain rule,` multiply this by the **partial derivative** of the subsequent, outer function, which is **`ReLU`**

We'll call these results the:

- `drelu_dxw0` - the partial **d**erivative of the **ReLU** w.r.t. the first weighted input, $w_0x_0$
- `drelu_dxw1` - the partial **d**erivative of the **ReLU** w.r.t. the first weighted input, $w_1x_1$
- `drelu_dxw2` - the partial **d**erivative of the **ReLU** w.r.t. the first weighted input, $w_2x_2$
- `drelu_db` - the partial **d**erivative of the **ReLU** w.r.t. the first weighted input, $b$

The **partial derivative**of the `sum operation` is always 1, no matter the inputs.

In [6]:
x = [1.0, -2.0, 3.0] 
w = [-3.0, -1.0, 2.0] 
b = 1.0 
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
z = xw0 + xw1 + xw2 + b
ReLU = max(z,0)
                   
dvalue = 1.0           

drelu_dz = dvalue * (1. if z > 0 else 0.)

# partial derivative of the sum with respect to the x (input), weighted, for the 0th pair of inputs and weights
dsum_dxw0 = 1
# partial derivative of the multiplication, the chain rule
drelu_dxw0 = drelu_dz * dsum_dxw0

dsum_dxw1 = 1
drelu_dxw1 = drelu_dz * dsum_dxw1


dsum_dxw2 = 1
drelu_dxw2 = drelu_dz * dsum_dxw2

dsum_db = 1
drelu_db = dsum_db * dsum_dxw2

print(f"{drelu_dxw0 = }\n{drelu_dxw1 = }\n{drelu_dxw2 = }\n{drelu_db = }\n")

drelu_dxw0 = 1.0
drelu_dxw1 = 1.0
drelu_dxw2 = 1.0
drelu_db = 1



Continuing backward, the function that comes before the sum is the **multiplication of weights and inputs**.

The derivative for a product is whatever the input is being multiplied by:

<font size="5">$f(x,y) = x * y → \frac{\partial}{\partial x}f(x,y) = y$</font>

<font size="5">$f(x,y) = x * y → \frac{\partial}{\partial y}f(x,y) = x$</font>

Following this rule, the partial derivative for the first _weighted input_ with respect to the _input_ simply equals the weight

-----

Then, we apply the **chain rule** and multiply this partial derivative with the partial derivative of the subsequent function, which is the sum

In [ ]:
dmul_dx0 = w[0]

drelu_dx0 = drelu_dxw0 * dmul_dx0

By working our way backward, taking the derivative of `ReLU` , the derivative of `sum` and multiplyig both, and so on, we are performing **`backpropagation`** using the **chain rule**.

As the name implies, the resulting `output function's gradients` are **passed back through the neural network**, using `multiplication of the gradient of subsequent functions` from later layers with the current one



In [9]:
x = [1.0, -2.0, 3.0] 
w = [-3.0, -1.0, 2.0] 
b = 1.0 
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]
z = xw0 + xw1 + xw2 + b
ReLU = max(z,0)
                   
dvalue = 1.0
drelu_dz = dvalue * (1. if z > 0 else 0.)


# partial derivatives of the multipliation, chain rule
dsum_dxw0 = 1
dsum_dxw1 = 1
dsum_dxw2 = 1
dsum_db = 1

drelu_dxw0 = drelu_dz * dsum_dxw0
drelu_dxw1 = drelu_dz * dsum_dxw1
drelu_dxw2 = drelu_dz * dsum_dxw2
drelu_db = dsum_db * dsum_dxw2

dmul_dx0 = w[0]
dmul_dx1 = w[1]
dmul_dx2 = w[2]
dmul_dw0 = x[0]
dmul_dw1 = x[1]
dmul_dw2 = x[2]

drelu_dx0 = drelu_dxw0 * dmul_dx0
drelu_dw0 = drelu_dxw0 * dmul_dw0

drelu_dx1 = drelu_dxw1 * dmul_dx1
drelu_dw1 = drelu_dxw1 * dmul_dw1

drelu_dx2 = drelu_dxw2 * dmul_dx2
drelu_dw2 = drelu_dxw2 * dmul_dw2

In [10]:
# the gradients can also be represented as:
dx = [drelu_dx0, drelu_dx1, drelu_dx2]
dw = [drelu_dw0, drelu_dw1, drelu_dw2]
db = drelu_db

Continuing with the single neuron example, we can now apply these gradients to the weights to hopefully minimize the output. 

This is typically the purpose of the **`optimizer`**. For now, we can simplify for this example by applying a negative fraction of the gradient to the weights.

We apply this negative fraction to the gradient since we want to **decrease the final output value**. 

Essentially, the `gradient` shows us the direction of the **steepest ascent**, so we negate it to go in the direction of the **steepest descent**

In [13]:
w[0] += -.001 * dw[0]
w[1] += -.001 * dw[1]
w[2] += -.001 * dw[2]
b += -.001 * db
print(w,b)


[-3.001, -0.998, 1.997] 0.999


Now, we've slightly changed the weights and bias **to decrease the output somewhat intelligently**.

We can see the effects of our tweaks on the output by doing another `forward pass`:


In [14]:
xw0 = x[0] * w[0]
xw1 = x[1] * w[1]
xw2 = x[2] * w[2]

z = xw0 + xw1 + xw2 + b

ReLU = max(z, 0)
print(ReLU)

5.985



Note that in real NNs, decreasing the neuron output is not the goal. We were doing this purely for this exercise. 

Instead, we need to decrease the **loss value**.

------

Instead of performing backprop on a single neuron, lets move to a `layer of neurons`:

- 3 samples of input
- Each sample contains 4 features

In [24]:
import numpy as np


# passed in gradient from the next layer (aka the gradient of the subsequent function)
# for this example, we're going to use a one-vector
dvalues = np.ones(shape=(1,3))

# we have 3 sets of weights --- one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5,],
                    [-0.26, -0.27, 0.17, 0.87]]).T

# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dx0 = sum(weights[0] * dvalues[0])
dx1 = sum(weights[1] * dvalues[0])
dx2 = sum(weights[2] * dvalues[0])
dx3 = sum(weights[3] * dvalues[0])

# gradient of the neuron function with respect to inputs
dinputs = np.array([dx0, dx1, dx2, dx3])
print(dinputs)



[ 0.44 -0.38 -0.07  1.37]


We can simplify the `summation` and `multiplication` as a **`dot product`**.

We need the output of `np.dot` to be of the shape of the gradient from the subsequent function.

In [31]:
# passed in gradient from the next layer (aka the gradient of the subsequent function)
# for this example, we're going to use a one-vector
dvalues = np.array([[1., 1., 1.],
                    [2., 2., 2.,],
                    [3., 3., 3.]])

inputs = np.array([[1, 2, 3, 3.5],
                   [2., 5., -1., 2],
                   [-1.5, 2.7, 3.3, -0.8]])

# we have 3 sets of weights --- one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5,],
                    [-0.26, -0.27, 0.17, 0.87]]).T

# gradient of the neuron function with respect to the weights
dweights = np.dot(inputs.T, dvalues)




In [34]:
# one bias for each neuron
# biases are the row vector with a shape (1, neurons)
biases = np.array([[2, 3, 0.5]])

# dbiases - sum values, do this over samples (first axis), keepdims
# since this by default will produce an array (this param keeps the dimension of the input, in this case a matrix or 2D-array)
dbiases = np.sum(dvalues, axis=0, keepdims=True)


array([[6., 6., 6.]])

In [36]:
z = np.array([[1, 2,-3, -4],
              [2, -7, -1, 3],
              [-1, 2, 5, -1]])

dvalues = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

# ReLU's derivative
drelu = np.zeros_like(z) # zeros_like creates an array of same shape as input array
drelu[z > 0] = 1 # performs element-wise comparison between drelu(zero matrix) and z

# chain rule
drelu *= dvalues

drelu


array([[ 1,  2,  0,  0],
       [ 5,  0,  0,  8],
       [ 0, 10, 11,  0]])

In [37]:
z = np.array([[1, 2,-3, -4],
              [2, -7, -1, 3],
              [-1, 2, 5, -1]])

dvalues = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

drelu = dvalues.copy()
drelu[z <= 0] = 0
drelu

array([[ 1,  2,  0,  0],
       [ 5,  0,  0,  8],
       [ 0, 10, 11,  0]])

Lets combine the **forward** and **backward** pass of a single neuron with a full layer and batch-based partial derivatives.

Again, we'll **minimize ReLU output** only for this example:

In [39]:
# passed-in gradient from the next layer
# for this example, were going to use
# an array of incremental gradient values
dvalues = np.array([[1,1,1],
                    [2,2,2],
                    [3,3,3]])

# we have 3 sets of inputs - samples
inputs = np.array([[1,2,3,2.5],
                   [2,5,-1,2],
                   [-1.5, 2.7, 3.3, -0.8]])

weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

biases = np.array([[2,3,0.5]])

# forward pass
layer_outputs = np.dot(inputs, weights) + biases # Dense layer
relu_outputs = np.maximum(0, layer_outputs)

drelu = relu_outputs.copy()
drelu[layer_outputs <= 0] = 0

# Dense layer
# dinputs - multiply by weights
dinputs = np.dot(drelu, weights.T)

dweights = np.dot(inputs.T, drelu)

dbiases = np.sum(drelu, axis=0, keepdims=True)

weights += -0.001 * dweights
biases += -0.001 * dbiases

print(weights,biases, sep="\n")

[[ 0.179515   0.5003665 -0.262746 ]
 [ 0.742093  -0.9152577 -0.2758402]
 [-0.510153   0.2529017  0.1629592]
 [ 0.971328  -0.5021842  0.8636583]]
[[1.98489  2.997739 0.497389]]
